baseURL = '/'          # 网站域名（部署时必须正确设置）
languageCode = 'zh-CN'  # 语言代码（如en-US、ja-JP）
title = '笔记记录'
theme = 'ananke'

# Theme parameters
[params]
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  site_logo = ""
  description = "The last theme you'll ever need"
  body_classes = "avenir bg-near-white"

# Menu Configuration
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/post/"
    weight = 1


# Outputs configuration
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML"]
  term = ["HTML"]
